### PR TITLE
Move client generation to CLI methods

### LINKED ISSUE #42: Fix login requests
At the moment we have a login request when executing e.g. `cobbler completion *` which is not intended. We should implement a kind of blacklist where commands are listed that do not require logins.

Examples:
```bash
$ make build
building package
go build -o cobbler main.go
creating shell completions
make shell_completions
make[1]: Entering directory '/home/dom/git/cobblercli'
./cobbler completion bash > config/completions/bash/cobbler
Using config file: /home/dom/.cobbler.yaml
error! Failed to login: Post "http://127.0.0.1/cobbler_api": dial tcp 127.0.0.1:80: connect: connection refused
./cobbler completion fish > config/completions/fish/cobbler
Using config file: /home/dom/.cobbler.yaml
error! Failed to login: Post "http://127.0.0.1/cobbler_api": dial tcp 127.0.0.1:80: connect: connection refused
./cobbler completion powershell > config/completions/powershell/cobbler
Using config file: /home/dom/.cobbler.yaml
error! Failed to login: Post "http://127.0.0.1/cobbler_api": dial tcp 127.0.0.1:80: connect: connection refused
./cobbler completion zsh > config/completions/zsh/cobbler
Using config file: /home/dom/.cobbler.yaml
error! Failed to login: Post "http://127.0.0.1/cobbler_api": dial tcp 127.0.0.1:80: connect: connection refused
make[1]: Leaving directory '/home/dom/git/cobblercli'
```

```bash
$ ./cobbler completion zsh | less > cobbler.zsh
Using config file: /home/dom/.cobbler.yaml
error! Failed to login: Post "http://127.0.0.1/cobbler_api": dial tcp 127.0.0.1:80: connect: connection refused

```

Those messages are from `stderr`.

The login is handled here:
https://github.com/cobbler/cli/blob/b82d106bf18bb3f3b874214bece5ea2569b87d17/cmd/root.go#L82-L96

and executed in [`initconfig()`](https://github.com/cobbler/cli/blob/b82d106bf18bb3f3b874214bece5ea2569b87d17/cmd/root.go#L49).

### PR DESCRIPTION
**Pull request by SchoolGuy**
This is needed so when executing --help or generating the shell completion no login is attempted to be performed.

Fixes #42

Building the project can be now done without the exit status 1:

```
enno@dell-laptop ~/S/G/cobbler-cli (main)> make build
building package
go build -o cobbler main.go
creating shell completions
make shell_completions
make[1]: Verzeichnis „/home/enno/Sources/GolandProjects/cobbler-cli“ wird betreten
./cobbler completion bash > config/completions/bash/cobbler
./cobbler completion fish > config/completions/fish/cobbler
./cobbler completion powershell > config/completions/powershell/cobbler
./cobbler completion zsh > config/completions/zsh/cobbler
make[1]: Verzeichnis „/home/enno/Sources/GolandProjects/cobbler-cli“ wird verlassen
```

### CODE REVIEW

File: cmd/report.go [hunk 1]
```diff
@@ -17,6 +17,7 @@ most of the other Cobbler commands (currently: distro, profile, system, repo, im
 Identical to 'cobbler list'`,
 
 	Run: func(cmd *cobra.Command, args []string) {
+
```
Comment (tiltingpenguin) [inline cmd/report.go:20]: Command is missing here

**Review by tiltingpenguin — CHANGES_REQUESTED** [review]

**Review by tiltingpenguin — APPROVED** [review]
LGTM
